import { HttpException } from '@nestjs/common';

export const ErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  EMAIL_REQUIRED: 'EMAIL_REQUIRED',
  NICKNAME_REQUIRED: 'NICKNAME_REQUIRED',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  NICKNAME_TAKEN: 'NICKNAME_TAKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  GOOGLE_ACCOUNT_LOGIN_REQUIRED: 'GOOGLE_ACCOUNT_LOGIN_REQUIRED',
  EMAIL_ACCOUNT_EXISTS: 'EMAIL_ACCOUNT_EXISTS',
  INVALID_USER: 'INVALID_USER',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  REFRESH_TOKEN_MISSING: 'REFRESH_TOKEN_MISSING',
  GOOGLE_SIGNUP_SESSION_MISSING: 'GOOGLE_SIGNUP_SESSION_MISSING',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  STUDYROOM_NOT_FOUND: 'STUDYROOM_NOT_FOUND',
  INVALID_INVITE_CODE: 'INVALID_INVITE_CODE',
  ALREADY_MEMBER: 'ALREADY_MEMBER',
  STUDYROOM_MEMBER_LIMIT: 'STUDYROOM_MEMBER_LIMIT',
  NOT_STUDYROOM_MEMBER: 'NOT_STUDYROOM_MEMBER',
  TARGET_NOT_STUDYROOM_MEMBER: 'TARGET_NOT_STUDYROOM_MEMBER',
  OWNER_CANNOT_LEAVE: 'OWNER_CANNOT_LEAVE',
  OWNER_ONLY: 'OWNER_ONLY',
  ADMIN_ONLY: 'ADMIN_ONLY',
  DELETE_FORBIDDEN: 'DELETE_FORBIDDEN',
  ROOM_FULL: 'ROOM_FULL',
  JOIN_ROOM_FAILED: 'JOIN_ROOM_FAILED',
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  MESSAGE_SEND_FAILED: 'MESSAGE_SEND_FAILED',
  MESSAGE_FETCH_FAILED: 'MESSAGE_FETCH_FAILED',
  MESSAGE_DELETE_FAILED: 'MESSAGE_DELETE_FAILED',
  DEMO_ACCOUNT_READ_ONLY: 'DEMO_ACCOUNT_READ_ONLY',
  INVALID_CURRENT_PASSWORD: 'INVALID_CURRENT_PASSWORD',
  SAME_PASSWORD: 'SAME_PASSWORD',
  PASSWORD_CHANGE_NOT_ALLOWED: 'PASSWORD_CHANGE_NOT_ALLOWED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ErrorPayload {
  code: string;
  message: string;
}

export const toErrorPayload = (
  error: unknown,
  fallback: ErrorPayload,
): ErrorPayload => {
  if (!(error instanceof HttpException)) return fallback;

  const response = error.getResponse();
  const code =
    typeof response === 'object' && 'code' in response
      ? String(response.code)
      : fallback.code;

  return { code, message: error.message };
};
